# Enable cursor animations (number is the fade length in ms, e.g., 200)
cursor_trail 200
# Adjust how fast the trailing dots fade out
cursor_trail_decay 0.1 0.4
# background_image /home/shaeel/Pictures/wallpapers/nyan_last.jpg
background_image_layout scaled
# Set the minimum distance the cursor must move for the trail to appear
cursor_trail_start_threshold 1
font_family FiraCode Nerd Font


background_opacity 0.75
window_padding_width 10 0 50 0


# BEGIN_KITTY_THEME
# 1984 Dark
include current-theme.conf
# END_KITTY_THEME
initial_window_width  100c
initial_window_height 30c
remember_window_size  no
hide_window_decorations yes
tab_bar_edge top
enable_audio_bell no

