# -*- conf -*-
include=~/.config/foot/catppuccin-macchiato.ini
font=monospace:size=11
pad=8x8 center-when-maximized-and-fullscreen

[environment]
[security]
[bell]
[desktop-notifications]
[scrollback]
[url]

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[touch]

[csd]
preferred=server

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
font-increase=Control+plus Control+equal
font-decrease=Control+minus
font-reset=Control+0
spawn-terminal=Control+Shift+n

[search-bindings]
[url-bindings]
[text-bindings]
[mouse-bindings]

# vim: ft=dosini